site_name: DCW
repo_url: https://github.com/derekwisong/dcw
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Code Reference: reference/  

plugins:
  - mkdocstrings
  - search
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

extra_css:
- css/code_select.css

markdown_extensions:
  - admonition
  - abbr
  - pymdownx.details
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference