name: Build

on:
  workflow_call:
    inputs:
        python_version:
          description: "Python version"
          type: string
          required: false
          default: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
            python-version: ${{ inputs.python_version }}
      - name: Install dependencies
        run: |
            sudo apt install -y libsnappy-dev
            python -m pip install --upgrade pip
            pip install poetry
            poetry install
      - name: Build application
        run: |
            poetry build
      - name: Test with pytest
        run: |
            poetry run pytest
      - name: Build documentation
        run: |
            poetry run mkdocs build
      - uses: actions/upload-artifact@v2
        with:
            name: dist
            path: dist
      - uses: actions/upload-pages-artifact@v2
        with:
          path: site
